version: "3.8"

services:
  database:
    image: mysql:8
    container_name: kream-clone-mysql
    ports:
      - 3316:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100
  
  backend:
    image: kream-clone-deploy:0.0.4
    container_name: kream-clone-server
    command: npm start
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
volumes:
  mysql-data: